"""add columns in financial asset table

Revision ID: 22ebfd8902ac
Revises: 876c2ed0bc31
Create Date: 2024-12-05 14:29:37.409594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22ebfd8902ac'
down_revision: Union[str, None] = '876c2ed0bc31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('financial_asset_income', sa.Column('total_gross_taxable', sa.Integer(), server_default= '0'))
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('financial_asset_income', 'total_gross_taxable')
    # ### end Alembic commands ###
