"""add column in rent income master table

Revision ID: 4743c4d5f017
Revises: be61522053ae
Create Date: 2024-12-15 14:39:18.178790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4743c4d5f017'
down_revision: Union[str, None] = 'be61522053ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.add_column('rent_income_master', sa.Column('total_adjusted_advance', sa.Integer(), nullable=True))
    


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
   
    op.drop_column('rent_income_master', 'total_adjusted_advance')
    # ### end Alembic commands ###
