"""add employer info column in tables

Revision ID: 5ec29ca6d1dc
Revises: c2dc36a9aa9f
Create Date: 2024-12-19 11:59:50.411123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5ec29ca6d1dc'
down_revision: Union[str, None] = 'c2dc36a9aa9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('allowance_details', sa.Column('employer_info_id', sa.Integer()))
    op.create_foreign_key(None, 'allowance_details', 'employer_info', ['employer_info_id'], ['id'])
    
    op.add_column('perquisite_details', sa.Column('employer_info_id', sa.Integer()))
    op.create_foreign_key(None, 'perquisite_details', 'employer_info', ['employer_info_id'], ['id'])
    
    op.add_column('vehicle_facility_details', sa.Column('employer_info_id', sa.Integer()))
    op.create_foreign_key(None, 'vehicle_facility_details', 'employer_info', ['employer_info_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vehicle_facility_details', type_='foreignkey')
    op.drop_column('vehicle_facility_details', 'employer_info_id')
    
    op.drop_constraint(None, 'perquisite_details', type_='foreignkey')
    op.drop_column('perquisite_details', 'employer_info_id')
    
    op.drop_constraint(None, 'allowance_details', type_='foreignkey')
    op.drop_column('allowance_details', 'employer_info_id')
    # ### end Alembic commands ###
