"""add columns in financial asset table

Revision ID: 876c2ed0bc31
Revises: 7614ab5483bd
Create Date: 2024-12-05 11:46:28.690943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '876c2ed0bc31'
down_revision: Union[str, None] = '7614ab5483bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('financial_asset_income', sa.Column('total_net_income', sa.Integer(), server_default='0'))
    op.add_column('financial_asset_income', sa.Column('total_tax_deduction_at_source', sa.Integer(), server_default='0'))
    op.add_column('financial_asset_income', sa.Column('total_interest_on_loans', sa.Integer(), server_default='0'))
    op.add_column('financial_asset_income', sa.Column('total_allowable_expenditure', sa.Integer(), server_default='0'))
    op.add_column('financial_asset_income', sa.Column('total_taxable', sa.Integer(), server_default='0'))
    op.add_column('financial_asset_income', sa.Column('total_gross_income', sa.Integer(), server_default='0'))
    op.add_column('financial_asset_income', sa.Column('total_gross_expense', sa.Integer(), server_default='0'))
    op.add_column('financial_asset_income', sa.Column('total_gross_exampted', sa.Integer(), server_default='0'))
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('financial_asset_income', 'total_gross_exampted')
    op.drop_column('financial_asset_income', 'total_gross_expense')
    op.drop_column('financial_asset_income', 'total_gross_income')
    op.drop_column('financial_asset_income', 'total_taxable')
    op.drop_column('financial_asset_income', 'total_allowable_expenditure')
    op.drop_column('financial_asset_income', 'total_interest_on_loans')
    op.drop_column('financial_asset_income', 'total_tax_deduction_at_source')
    op.drop_column('financial_asset_income', 'total_net_income')
    # ### end Alembic commands ###
