"""add flat count in rent income

Revision ID: 87c4ba53261b
Revises: 4743c4d5f017
Create Date: 2024-12-17 10:49:49.987728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '87c4ba53261b'
down_revision: Union[str, None] = '4743c4d5f017'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rent_income_master', sa.Column('total_flats', sa.Integer(), nullable=True))
    op.add_column('rent_income_master', sa.Column('total_flats_on_rent', sa.Integer(), nullable=True))
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.drop_column('rent_income_master', 'total_flats_on_rent')
    op.drop_column('rent_income_master', 'total_flats')
    # ### end Alembic commands ###
