"""create rent income table

Revision ID: 94daddb4dc9e
Revises: 0a41d18699fb
Create Date: 2024-12-11 11:19:39.837715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '94daddb4dc9e'
down_revision: Union[str, None] = '0a41d18699fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - adjusted for improvements ###
    op.create_table('rent_income',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('area_type', sa.Enum('residential', 'business', 'other', name='areatype'), server_default='residential'),
        sa.Column('asset_name', sa.String(length=100), nullable=False),
        sa.Column('asset_address', sa.String(length=500), nullable=False),
        sa.Column('total_income', sa.Integer(),  server_default='0'),
        sa.Column('total_expense', sa.Integer(),  server_default='0'),
        sa.Column('special_income', sa.Integer(),  server_default='0'),
        sa.Column('net_income', sa.Integer(),  server_default='0'),
        sa.Column('rent_taken', sa.Integer(),  server_default='0'),
        sa.Column('yearly_value', sa.Integer(),  server_default='0'),
        sa.Column('adjusted_advance', sa.Integer(),  server_default='0'),
        sa.Column('other_charge', sa.Integer(),  server_default='0'),
        sa.Column('other_taken_rent', sa.Integer(),  server_default='0'),
        sa.Column('vacancy_allowance', sa.Integer(),  server_default='0'),
        sa.Column('insurance_premium_paid_actual', sa.Integer(),  server_default='0'),
        sa.Column('insurance_premium_paid_allowable', sa.Integer(),  server_default='0'),
        sa.Column('interest_on_repaid_loans_actual', sa.Integer(),  server_default='0'),
        sa.Column('interest_on_repaid_loans_allowable', sa.Integer(),  server_default='0'),
        sa.Column('land_revenue_actual', sa.Integer(),  server_default='0'),
        sa.Column('land_revenue_allowable', sa.Integer(),  server_default='0'),
        sa.Column('municipal_or_local_tax_actual', sa.Integer(),  server_default='0'),
        sa.Column('municipal_or_local_tax_allowable', sa.Integer(),  server_default='0'),
        sa.Column('receipt_of_repairs_actual', sa.Integer(),  server_default='0'),
        sa.Column('receipt_of_repairs_allowable', sa.Integer(),  server_default='0'),
        sa.Column('space_type', sa.String(length=100), nullable=False),
        sa.Column('live_ownself', sa.Enum('yes', 'no', name='liveownself'), nullable=True),
        sa.Column('monthly_rent', sa.Integer(),  server_default='0'),
        sa.Column('monthly_service_charge', sa.Integer(),  server_default='0'),
        sa.Column('advance', sa.Integer(),  server_default='0'),
        sa.Column('adjusted_rent', sa.Integer(),  server_default='0'),
        sa.Column('total_rent', sa.Integer(),  server_default='0'),
        sa.Column('total_rent_received', sa.Integer(),  server_default='0'),
        sa.Column('total_service_charge_received', sa.Integer(),  server_default='0'),
        sa.Column('total_vacancy_rent', sa.Integer(),  server_default='0'),
        sa.Column('total_vacancy_month', sa.Integer(),  server_default='0'),
        sa.Column('january', sa.Enum('yes', 'no', name='months'),  server_default='no'),
        sa.Column('february', sa.Enum('yes', 'no', name='months'),  server_default='no'),
        sa.Column('march', sa.Enum('yes', 'no', name='months'),  server_default='no'),
        sa.Column('april', sa.Enum('yes', 'no', name='months'),  server_default='no'),
        sa.Column('may', sa.Enum('yes', 'no', name='months'),  server_default='no'),
        sa.Column('june', sa.Enum('yes', 'no', name='months'),  server_default='no'),
        sa.Column('july', sa.Enum('yes', 'no', name='months'),  server_default='no'),
        sa.Column('august', sa.Enum('yes', 'no', name='months'),  server_default='no'),
        sa.Column('september', sa.Enum('yes', 'no', name='months'),  server_default='no'),
        sa.Column('october', sa.Enum('yes', 'no', name='months'),  server_default='no'),
        sa.Column('november', sa.Enum('yes', 'no', name='months'),  server_default='no'),
        sa.Column('december', sa.Enum('yes', 'no', name='months'),  server_default='no'),
        sa.Column('gross_total_income', sa.Integer(),  server_default='0'),
        sa.Column('gross_total_expense', sa.Integer(),  server_default='0'),
        sa.Column('gross_net_income', sa.Integer(),  server_default='0'),
        sa.Column('etin', sa.String(length=12), nullable=False),
        sa.ForeignKeyConstraint(['etin'], ['taxpayer.etin'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('rent_income_id_idx', 'rent_income', ['id'], unique=True)

def downgrade() -> None:
    # ### commands auto generated by Alembic - adjusted for improvements ###
    op.drop_index('rent_income_id_idx', table_name='rent_income')
    op.drop_table('rent_income')
