"""add transportation in allowance

Revision ID: c2dc36a9aa9f
Revises: 87c4ba53261b
Create Date: 2024-12-18 13:19:10.916002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c2dc36a9aa9f'
down_revision: Union[str, None] = '87c4ba53261b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('perquisite_details', sa.Column('transportation_allowance', sa.Integer(), nullable=True))
    op.add_column('perquisite_details', sa.Column('transportation_allowance_remarks', sa.String(length=100), nullable=True))
   

def downgrade() -> None:
    
    op.drop_column('perquisite_details', 'transportation_allowance_remarks')
    op.drop_column('perquisite_details', 'transportation_allowance')
    # ### end Alembic commands ###
