"""create financial asset income table

Revision ID: c40fae7953cd
Revises: 96dff94a23c6
Create Date: 2024-12-08 15:59:23.900041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c40fae7953cd'
down_revision: Union[str, None] = '96dff94a23c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('financial_asset_income',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('savings_ban_interest_net_income', sa.Integer(), nullable=True),
    sa.Column('savings_ban_interest_tax_deduction_at_source', sa.Integer(), nullable=True),
    sa.Column('savings_ban_interest_interest_on_loans', sa.Integer(), nullable=True),
    sa.Column('savings_ban_interest_allowable_expenditure', sa.Integer(), nullable=True),
    sa.Column('savings_ban_interest_taxable', sa.Integer(), nullable=True),
    sa.Column('savings_ban_interest_description', sa.String(), nullable=True),
    sa.Column('other_securities_net_income', sa.Integer(), nullable=True),
    sa.Column('other_securities_tax_deduction_at_source', sa.Integer(), nullable=True),
    sa.Column('other_securities_interest_on_loans', sa.Integer(), nullable=True),
    sa.Column('other_securities_allowable_expenditure', sa.Integer(), nullable=True),
    sa.Column('other_securities_taxable', sa.Integer(), nullable=True),
    sa.Column('other_securities_description', sa.String(), nullable=True),
    sa.Column('income_from_islamic_principles_net_income', sa.Integer(), nullable=True),
    sa.Column('income_from_islamic_principles_tax_deduction_at_source', sa.Integer(), nullable=True),
    sa.Column('income_from_islamic_principles_interest_on_loans', sa.Integer(), nullable=True),
    sa.Column('income_from_islamic_principles_allowable_expenditure', sa.Integer(), nullable=True),
    sa.Column('income_from_islamic_principles_taxable', sa.Integer(), nullable=True),
    sa.Column('income_from_islamic_principles_description', sa.String(), nullable=True),
    sa.Column('bank_interest_savings_deposits_net_income', sa.Integer(), nullable=True),
    sa.Column('bank_interest_savings_deposits_tax_deduction_at_source', sa.Integer(), nullable=True),
    sa.Column('bank_interest_savings_deposits_interest_on_loans', sa.Integer(), nullable=True),
    sa.Column('bank_interest_savings_deposits_allowable_expenditure', sa.Integer(), nullable=True),
    sa.Column('bank_interest_savings_deposits_taxable', sa.Integer(), nullable=True),
    sa.Column('bank_interest_savings_deposits_description', sa.String(), nullable=True),
    sa.Column('fdr_interest_income_net_income', sa.Integer(), nullable=True),
    sa.Column('fdr_interest_income_tax_deduction_at_source', sa.Integer(), nullable=True),
    sa.Column('fdr_interest_income_interest_on_loans', sa.Integer(), nullable=True),
    sa.Column('fdr_interest_income_allowable_expenditure', sa.Integer(), nullable=True),
    sa.Column('fdr_interest_income_taxable', sa.Integer(), nullable=True),
    sa.Column('fdr_interest_income_description', sa.String(), nullable=True),
    sa.Column('dividend_income_net_income', sa.Integer(), nullable=True),
    sa.Column('dividend_income_tax_deduction_at_source', sa.Integer(), nullable=True),
    sa.Column('dividend_income_interest_on_loans', sa.Integer(), nullable=True),
    sa.Column('dividend_income_allowable_expenditure', sa.Integer(), nullable=True),
    sa.Column('dividend_income_taxable', sa.Integer(), nullable=True),
    sa.Column('dividend_income_description', sa.String(), nullable=True),
    sa.Column('total_net_income', sa.Integer(), nullable=True),
    sa.Column('total_tax_deduction_at_source', sa.Integer(), nullable=True),
    sa.Column('total_interest_on_loans', sa.Integer(), nullable=True),
    sa.Column('total_allowable_expenditure', sa.Integer(), nullable=True),
    sa.Column('total_taxable', sa.Integer(), nullable=True),
    sa.Column('reduced_tax_rate_securities_net_income', sa.Integer(), nullable=True),
    sa.Column('reduced_tax_rate_securities_tax_deduction_at_source', sa.Integer(), nullable=True),
    sa.Column('reduced_tax_rate_securities_interest_on_loans', sa.Integer(), nullable=True),
    sa.Column('reduced_tax_rate_securities_allowable_expenditure', sa.Integer(), nullable=True),
    sa.Column('reduced_tax_rate_securities_taxable', sa.Integer(), nullable=True),
    sa.Column('reduced_tax_rate_securities_description', sa.String(), nullable=True),
    sa.Column('income_other_resources_net_income', sa.Integer(), nullable=True),
    sa.Column('income_other_resources_tax_deduction_at_source', sa.Integer(), nullable=True),
    sa.Column('income_other_resources_interest_on_loans', sa.Integer(), nullable=True),
    sa.Column('income_other_resources_allowable_expenditure', sa.Integer(), nullable=True),
    sa.Column('income_other_resources_taxable', sa.Integer(), nullable=True),
    sa.Column('income_other_resources_description', sa.String(), nullable=True),
    sa.Column('us_dollar_investment_bonds_net_income', sa.Integer(), nullable=True),
    sa.Column('us_dollar_investment_bonds_tax_deduction_at_source', sa.Integer(), nullable=True),
    sa.Column('us_dollar_investment_bonds_interest_on_loans', sa.Integer(), nullable=True),
    sa.Column('us_dollar_investment_bonds_exampted_amount', sa.Integer(), nullable=True),
    sa.Column('us_dollar_investment_bonds_allowable_expenditure', sa.Integer(), nullable=True),
    sa.Column('us_dollar_investment_bonds_taxable', sa.Integer(), nullable=True),
    sa.Column('us_dollar_investment_bonds_description', sa.String(), nullable=True),
    sa.Column('euro_premium_bonds_net_income', sa.Integer(), nullable=True),
    sa.Column('euro_premium_bonds_tax_deduction_at_source', sa.Integer(), nullable=True),
    sa.Column('euro_premium_bonds_interest_on_loans', sa.Integer(), nullable=True),
    sa.Column('euro_premium_bonds_exampted_amount', sa.Integer(), nullable=True),
    sa.Column('euro_premium_bonds_allowable_expenditure', sa.Integer(), nullable=True),
    sa.Column('euro_premium_bonds_taxable', sa.Integer(), nullable=True),
    sa.Column('euro_premium_bonds_description', sa.String(), nullable=True),
    sa.Column('pound_sterling_premium_bonds_net_income', sa.Integer(), nullable=True),
    sa.Column('pound_sterling_premium_bonds_tax_deduction_at_source', sa.Integer(), nullable=True),
    sa.Column('pound_sterling_premium_bonds_interest_on_loans', sa.Integer(), nullable=True),
    sa.Column('pound_sterling_premium_bonds_exampted_amount', sa.Integer(), nullable=True),
    sa.Column('pound_sterling_premium_bonds_allowable_expenditure', sa.Integer(), nullable=True),
    sa.Column('pound_sterling_premium_bonds_taxable', sa.Integer(), nullable=True),
    sa.Column('pound_sterling_premium_bonds_description', sa.String(), nullable=True),
    sa.Column('us_dollar_premium_bonds_net_income', sa.Integer(), nullable=True),
    sa.Column('us_dollar_premium_bonds_tax_deduction_at_source', sa.Integer(), nullable=True),
    sa.Column('us_dollar_premium_bonds_interest_on_loans', sa.Integer(), nullable=True),
    sa.Column('us_dollar_premium_bonds_exampted_amount', sa.Integer(), nullable=True),
    sa.Column('us_dollar_premium_bonds_allowable_expenditure', sa.Integer(), nullable=True),
    sa.Column('us_dollar_premium_bonds_taxable', sa.Integer(), nullable=True),
    sa.Column('us_dollar_premium_bonds_description', sa.String(), nullable=True),
    sa.Column('wage_earners_development_bonds_net_income', sa.Integer(), nullable=True),
    sa.Column('wage_earners_development_bonds_tax_deduction_at_source', sa.Integer(), nullable=True),
    sa.Column('wage_earners_development_bonds_interest_on_loans', sa.Integer(), nullable=True),
    sa.Column('wage_earners_development_bonds_exampted_amount', sa.Integer(), nullable=True),
    sa.Column('wage_earners_development_bonds_allowable_expenditure', sa.Integer(), nullable=True),
    sa.Column('wage_earners_development_bonds_taxable', sa.Integer(), nullable=True),
    sa.Column('wage_earners_development_bonds_description', sa.String(), nullable=True),
    sa.Column('euro_investment_bonds_net_income', sa.Integer(), nullable=True),
    sa.Column('euro_investment_bonds_tax_deduction_at_source', sa.Integer(), nullable=True),
    sa.Column('euro_investment_bonds_interest_on_loans', sa.Integer(), nullable=True),
    sa.Column('euro_investment_bonds_exampted_amount', sa.Integer(), nullable=True),
    sa.Column('euro_investment_bonds_allowable_expenditure', sa.Integer(), nullable=True),
    sa.Column('euro_investment_bonds_taxable', sa.Integer(), nullable=True),
    sa.Column('euro_investment_bonds_description', sa.String(), nullable=True),
    sa.Column('total_gross_income', sa.Integer(), nullable=True),
    sa.Column('total_gross_expense', sa.Integer(), nullable=True),
    sa.Column('total_gross_exampted', sa.Integer(), nullable=True),
    sa.Column('total_gross_taxable', sa.Integer(), nullable=True),
    sa.Column('etin', sa.String(length=12), nullable=False),
    sa.ForeignKeyConstraint(['etin'], ['taxpayer.etin'], ),
    sa.PrimaryKeyConstraint('id')
    )
   
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('financial_asset_income')
    # ### end Alembic commands ###
